### PR TITLE
Turkish language added

### PR DESCRIPTION
**Pull request by alisincar**

### CODE REVIEW

**Comment by helmasaur** [comment]
Sorry, I didn't see your pull request. I'll look through this before next week 😊 !

**Comment by alisincar** [comment]
ok, no problem, i'll be waiting 😊

**Review by helmasaur — APPROVED** [review]
I checked all translations and it's all good. Thank you very much for your work 😊 !

**Comment by helmasaur** [comment]
Your translation is avaible on npm 🎉 !

**Pull request merged**
