### PR TITLE
Added spanish translation

### PR DESCRIPTION
**Pull request by VitoMars**
This is a branch starting from the German translation in which I have also inserted the Spanish translation.

### CODE REVIEW

**Comment by helmasaur** [comment]
Could you please create a branch for Spanish which would be aside of the German one?

**Comment by VitoMars** [comment]
> Could you please create a branch for Spanish which would be aside of the German one?

I directly updated this branch, now it contains only the changes of adding the Spanish language

**Comment by helmasaur** [comment]
Thank you very much! I will add it in the next version coming before the month.

**Review by helmasaur — APPROVED** [review]
All good 😁 !

**Pull request merged**
